export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILED';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILED';

export const LOGOUT = 'LOGOUT';


export const LIST_USERS_REQUEST = 'LIST_USERS_REQUEST';
export const LIST_USERS_SUCCESS = 'LIST_USERS_SUCCESS';
export const LIST_USERS_FAILURE = 'LIST_USERS_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';


export const LIST_MOVIES_REQUEST = 'LIST_MOVIES_REQUEST';
export const LIST_MOVIES_SUCCESS = 'LIST_MOVIES_SUCCESS';
export const LIST_MOVIES_FAILURE = 'LIST_MOVIES_FAILURE';

export const LIST_RECOMMENDED_MOVIES_REQUEST = 'LIST_RECOMMENDED_MOVIES_REQUEST';
export const LIST_RECOMMENDED_MOVIES_SUCCESS = 'LIST_RECOMMENDED_MOVIES_SUCCESS';
export const LIST_RECOMMENDED_MOVIES_FAILURE = 'LIST_RECOMMENDED_MOVIES_FAILURE';

export const LIST_WATCHED_MOVIES_REQUEST = 'LIST_WATCHED_MOVIES_REQUEST';
export const LIST_WATCHED_MOVIES_SUCCESS = 'LIST_WATCHED_MOVIES_SUCCESS';
export const LIST_WATCHED_MOVIES_FAILURE = 'LIST_WATCHED_MOVIES_FAILURE';

export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';

export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILURE = 'GET_MOVIE_FAILURE';

export const CREATE_MOVIE_REQUEST = 'CREATE_MOVIE_REQUEST';
export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS';
export const CREATE_MOVIE_FAILURE = 'CREATE_MOVIE_FAILURE';

export const UPDATE_MOVIE_REQUEST = 'UPDATE_MOVIE_REQUEST';
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS';
export const UPDATE_MOVIE_FAILURE = 'UPDATE_MOVIE_FAILURE';

export const DELETE_MOVIE_REQUEST = 'DELETE_MOVIE_REQUEST';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE';

export const LOAD_MOVIE_FROM_OMDB_REQUEST = 'LOAD_MOVIE_FROM_OMDB_REQUEST';
export const LOAD_MOVIE_FROM_OMDB_SUCCESS = 'LOAD_MOVIE_FROM_OMDB_SUCCESS';
export const LOAD_MOVIE_FROM_OMDB_FAILURE = 'LOAD_MOVIE_FROM_OMDB_FAILURE';

export const LIST_GENRES_REQUEST = 'LIST_GENRES_REQUEST';
export const LIST_GENRES_SUCCESS = 'LIST_GENRES_SUCCESS';
export const LIST_GENRES_FAILURE = 'LIST_GENRES_FAILURE';

export const LIST_TAGS_REQUEST = 'LIST_TAGS_REQUEST';
export const LIST_TAGS_SUCCESS = 'LIST_TAGS_SUCCESS';
export const LIST_TAGS_FAILURE = 'LIST_TAGS_FAILURE';

export const ADD_MOVIE_PHOTO = 'ADD_MOVIE_PHOTO';
